/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense, useEffect } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'


const useAnimateGroup = (groupRef, options) => {
    useEffect(() => {
        if (groupRef.current) {
            groupRef.current.children.forEach(mesh => {
                mesh.userData.initialY = mesh.position.y;
                mesh.userData.targetY = Math.random() * (options.range) + options.min;
                mesh.userData.animationProgress = 0;
            });
        }
    }, [groupRef, options]);

    useFrame((state, delta) => {
        if (groupRef.current) {
            groupRef.current.children.forEach(mesh => {
                if (mesh.userData.animationProgress < 1) {
                    mesh.userData.animationProgress += delta / options.duration;
                    const progress = mesh.userData.animationProgress;
                    mesh.position.y = mesh.userData.initialY + (mesh.userData.targetY - mesh.userData.initialY) * progress;

                    // Reset animation if complete
                    if (progress >= 1) {
                        mesh.userData.initialY = mesh.userData.targetY;
                        mesh.userData.targetY = options.resetTargetY;
                        mesh.userData.animationProgress = 0;
                    }
                }
            });
        }
    });
};


export default function Gamer(props) {

    const { nodes, materials } = useGLTF("./models/gamer.glb");

    const mesh_ref = useRef();
    const floor_group_ref = useRef();
    const wall_group_ref = useRef();
    const desk_group_ref = useRef();
    const monitor_group_ref = useRef();
    const couch_group_ref = useRef();
    const wallmonitors_group_ref = useRef();



    // Use the hook for floor group
    useAnimateGroup(floor_group_ref, { range: -20, min: -10, duration: 2.2, resetTargetY: 0 });

    // Use the hook for wall group
    useAnimateGroup(wall_group_ref, { range: 20, min: 10, duration: 2, resetTargetY: 0.5 });

    useAnimateGroup(desk_group_ref, { range: 20, min: 10, duration: 2.3, resetTargetY: 0 });
    useAnimateGroup(monitor_group_ref, { range: 21, min: 20, duration: 2.4, resetTargetY: 0.5 });
    useAnimateGroup(couch_group_ref, { range: 30, min: 20, duration: 2.5, resetTargetY: 0.1 });
    useAnimateGroup(wallmonitors_group_ref, { range: 30, min: 20, duration: 2.6, resetTargetY: 3.5 });

    const open_github = () => {
        window.open("https://github.com/MaxwellVolz")
    }

    return (

        <group {...props} dispose={null} scale={1}>
            <group ref={floor_group_ref}>
                <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
                <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[1, 0, 0]} />
                <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[2, 0, 0]} />
                <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[3, 0, 0]} />
                <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[4, 0, 0]} />
                <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[5, 0, 0]} />
                <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-5, 0, 0]} />
                <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-4, 0, 0]} />
                <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-3, 0, 0]} />
                <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-2, 0, 0]} />
                <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[-1, 0, 0]} />
                <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0, 0, 1]} />
                <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[1, 0, 1]} />
                <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2, 0, 1]} />
                <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[3, 0, 1]} />
                <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[4, 0, 1]} />
                <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[5, 0, 1]} />
                <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-5, 0, 1]} />
                <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-4, 0, 1]} />
                <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-3, 0, 1]} />
                <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[-2, 0, 1]} />
                <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-1, 0, 1]} />
                <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[0, 0, 2]} />
                <mesh geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[1, 0, 2]} />
                <mesh geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[2, 0, 2]} />
                <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[3, 0, 2]} />
                <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[4, 0, 2]} />
                <mesh geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[5, 0, 2]} />
                <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[-5, 0, 2]} />
                <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[-4, 0, 2]} />
                <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[-3, 0, 2]} />
                <mesh geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[-2, 0, 2]} />
                <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[-1, 0, 2]} />
                <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[0, 0, 3]} />
                <mesh geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} position={[1, 0, 3]} />
                <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[2, 0, 3]} />
                <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[3, 0, 3]} />
                <mesh geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[4, 0, 3]} />
                <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[5, 0, 3]} />
                <mesh geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[-5, 0, 3]} />
                <mesh geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[-4, 0, 3]} />
                <mesh geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[-3, 0, 3]} />
                <mesh geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[-2, 0, 3]} />
                <mesh geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[-1, 0, 3]} />
                <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[0, 0, 4]} />
                <mesh geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[1, 0, 4]} />
                <mesh geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[2, 0, 4]} />
                <mesh geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[3, 0, 4]} />
                <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[4, 0, 4]} />
                <mesh geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[5, 0, 4]} />
                <mesh geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[-5, 0, 4]} />
                <mesh geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[-4, 0, 4]} />
                <mesh geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[-3, 0, 4]} />
                <mesh geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[-2, 0, 4]} />
                <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[-1, 0, 4]} />
                <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[0, 0, 5]} />
                <mesh geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[1, 0, 5]} />
                <mesh geometry={nodes.Cube057.geometry} material={nodes.Cube057.material} position={[2, 0, 5]} />
                <mesh geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[3, 0, 5]} />
                <mesh geometry={nodes.Cube059.geometry} material={nodes.Cube059.material} position={[4, 0, 5]} />
                <mesh geometry={nodes.Cube060.geometry} material={nodes.Cube060.material} position={[5, 0, 5]} />
                <mesh geometry={nodes.Cube061.geometry} material={nodes.Cube061.material} position={[-5, 0, 5]} />
                <mesh geometry={nodes.Cube062.geometry} material={nodes.Cube062.material} position={[-4, 0, 5]} />
                <mesh geometry={nodes.Cube063.geometry} material={nodes.Cube063.material} position={[-3, 0, 5]} />
                <mesh geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} position={[-2, 0, 5]} />
                <mesh geometry={nodes.Cube065.geometry} material={nodes.Cube065.material} position={[-1, 0, 5]} />
                <mesh geometry={nodes.Cube066.geometry} material={nodes.Cube066.material} position={[0, 0, 6]} />
                <mesh geometry={nodes.Cube067.geometry} material={nodes.Cube067.material} position={[1, 0, 6]} />
                <mesh geometry={nodes.Cube068.geometry} material={nodes.Cube068.material} position={[2, 0, 6]} />
                <mesh geometry={nodes.Cube069.geometry} material={nodes.Cube069.material} position={[3, 0, 6]} />
                <mesh geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[4, 0, 6]} />
                <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[5, 0, 6]} />
                <mesh geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[-5, 0, 6]} />
                <mesh geometry={nodes.Cube073.geometry} material={nodes.Cube073.material} position={[-4, 0, 6]} />
                <mesh geometry={nodes.Cube074.geometry} material={nodes.Cube074.material} position={[-3, 0, 6]} />
                <mesh geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[-2, 0, 6]} />
                <mesh geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[-1, 0, 6]} />
                <mesh geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[-6, 0, 0]} />
                <mesh geometry={nodes.Cube079.geometry} material={nodes.Cube079.material} position={[-6, 0, 1]} />
                <mesh geometry={nodes.Cube080.geometry} material={nodes.Cube080.material} position={[-6, 0, 2]} />
                <mesh geometry={nodes.Cube081.geometry} material={nodes.Cube081.material} position={[-6, 0, 3]} />
                <mesh geometry={nodes.Cube082.geometry} material={nodes.Cube082.material} position={[-6, 0, 4]} />
                <mesh geometry={nodes.Cube083.geometry} material={nodes.Cube083.material} position={[-6, 0, 5]} />
                <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} position={[-6, 0, 6]} />
                <mesh geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[6, 0, 0]} />
                <mesh geometry={nodes.Cube086.geometry} material={nodes.Cube086.material} position={[6, 0, 1]} />
                <mesh geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} position={[6, 0, 2]} />
                <mesh geometry={nodes.Cube088.geometry} material={nodes.Cube088.material} position={[6, 0, 3]} />
                <mesh geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} position={[6, 0, 4]} />
                <mesh geometry={nodes.Cube090.geometry} material={nodes.Cube090.material} position={[6, 0, 5]} />
                <mesh geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[6, 0, 6]} />
                <mesh geometry={nodes.Cube092.geometry} material={nodes.Cube092.material} position={[0, 0, 7]} />
                <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[1, 0, 7]} />
                <mesh geometry={nodes.Cube094.geometry} material={nodes.Cube094.material} position={[2, 0, 7]} />
                <mesh geometry={nodes.Cube095.geometry} material={nodes.Cube095.material} position={[3, 0, 7]} />
                <mesh geometry={nodes.Cube096.geometry} material={nodes.Cube096.material} position={[4, 0, 7]} />
                <mesh geometry={nodes.Cube097.geometry} material={nodes.Cube097.material} position={[5, 0, 7]} />
                <mesh geometry={nodes.Cube098.geometry} material={nodes.Cube098.material} position={[-5, 0, 7]} />
                <mesh geometry={nodes.Cube099.geometry} material={nodes.Cube099.material} position={[-4, 0, 7]} />
                <mesh geometry={nodes.Cube100.geometry} material={nodes.Cube100.material} position={[-3, 0, 7]} />
                <mesh geometry={nodes.Cube101.geometry} material={nodes.Cube101.material} position={[-2, 0, 7]} />
                <mesh geometry={nodes.Cube102.geometry} material={nodes.Cube102.material} position={[-1, 0, 7]} />
                <mesh geometry={nodes.Cube103.geometry} material={nodes.Cube103.material} position={[-6, 0, 7]} />
                <mesh geometry={nodes.Cube104.geometry} material={nodes.Cube104.material} position={[6, 0, 7]} />
                <mesh geometry={nodes.Cube105.geometry} material={nodes.Cube105.material} />
                <mesh geometry={nodes.Cube106.geometry} material={nodes.Cube106.material} position={[1, 0, 0]} />
                <mesh geometry={nodes.Cube107.geometry} material={nodes.Cube107.material} position={[2, 0, 0]} />
                <mesh geometry={nodes.Cube108.geometry} material={nodes.Cube108.material} position={[3, 0, 0]} />
                <mesh geometry={nodes.Cube109.geometry} material={nodes.Cube109.material} position={[4, 0, 0]} />
                <mesh geometry={nodes.Cube110.geometry} material={nodes.Cube110.material} position={[5, 0, 0]} />
                <mesh geometry={nodes.Cube111.geometry} material={nodes.Cube111.material} position={[-5, 0, 0]} />
                <mesh geometry={nodes.Cube112.geometry} material={nodes.Cube112.material} position={[-4, 0, 0]} />
                <mesh geometry={nodes.Cube113.geometry} material={nodes.Cube113.material} position={[-3, 0, 0]} />
                <mesh geometry={nodes.Cube114.geometry} material={nodes.Cube114.material} position={[-2, 0, 0]} />
                <mesh geometry={nodes.Cube115.geometry} material={nodes.Cube115.material} position={[-1, 0, 0]} />
                <mesh geometry={nodes.Cube116.geometry} material={nodes.Cube116.material} position={[-6, 0, 0]} />
                <mesh geometry={nodes.Cube117.geometry} material={nodes.Cube117.material} position={[6, 0, 0]} />
                <mesh geometry={nodes.Cube118.geometry} material={nodes.Cube118.material} position={[0, 0, -1]} />
                <mesh geometry={nodes.Cube119.geometry} material={nodes.Cube119.material} position={[1, 0, -1]} />
                <mesh geometry={nodes.Cube120.geometry} material={nodes.Cube120.material} position={[2, 0, -1]} />
                <mesh geometry={nodes.Cube121.geometry} material={nodes.Cube121.material} position={[3, 0, -1]} />
                <mesh geometry={nodes.Cube122.geometry} material={nodes.Cube122.material} position={[4, 0, -1]} />
                <mesh geometry={nodes.Cube123.geometry} material={nodes.Cube123.material} position={[5, 0, -1]} />
                <mesh geometry={nodes.Cube124.geometry} material={nodes.Cube124.material} position={[-5, 0, -1]} />
                <mesh geometry={nodes.Cube125.geometry} material={nodes.Cube125.material} position={[-4, 0, -1]} />
                <mesh geometry={nodes.Cube126.geometry} material={nodes.Cube126.material} position={[-3, 0, -1]} />
                <mesh geometry={nodes.Cube127.geometry} material={nodes.Cube127.material} position={[-2, 0, -1]} />
                <mesh geometry={nodes.Cube128.geometry} material={nodes.Cube128.material} position={[-1, 0, -1]} />
                <mesh geometry={nodes.Cube129.geometry} material={nodes.Cube129.material} position={[-6, 0, -1]} />
                <mesh geometry={nodes.Cube130.geometry} material={nodes.Cube130.material} position={[6, 0, -1]} />
            </group>
            <group ref={wall_group_ref}>
                <mesh geometry={nodes.Cube131.geometry} material={nodes.Cube131.material} position={[6.65, 0.5, -1]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube132.geometry} material={nodes.Cube132.material} position={[6.65, 0.5, 0]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube133.geometry} material={nodes.Cube133.material} position={[6.65, 0.5, 1]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube134.geometry} material={nodes.Cube134.material} position={[6.65, 0.5, 2]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube135.geometry} material={nodes.Cube135.material} position={[6.65, 0.5, 3]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube136.geometry} material={nodes.Cube136.material} position={[6.65, 0.5, 4]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube137.geometry} material={nodes.Cube137.material} position={[6.65, 0.5, 5]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube138.geometry} material={nodes.Cube138.material} position={[6.65, 0.5, 6]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube139.geometry} material={nodes.Cube139.material} position={[6.65, 0.5, 7]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube140.geometry} material={nodes.Cube140.material} position={[-6.65, 0.5, -1]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube141.geometry} material={nodes.Cube141.material} position={[-6.65, 0.5, 0]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube142.geometry} material={nodes.Cube142.material} position={[-6.65, 0.5, 1]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube143.geometry} material={nodes.Cube143.material} position={[-6.65, 0.5, 2]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube144.geometry} material={nodes.Cube144.material} position={[-6.65, 0.5, 3]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube145.geometry} material={nodes.Cube145.material} position={[-6.65, 0.5, 4]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube146.geometry} material={nodes.Cube146.material} position={[-6.65, 0.5, 5]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube147.geometry} material={nodes.Cube147.material} position={[-6.65, 0.5, 6]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube148.geometry} material={nodes.Cube148.material} position={[-6.65, 0.5, 7]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh geometry={nodes.Cube149.geometry} material={nodes.Cube149.material} position={[0, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube150.geometry} material={nodes.Cube150.material} position={[1, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube151.geometry} material={nodes.Cube151.material} position={[2, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube152.geometry} material={nodes.Cube152.material} position={[3, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube153.geometry} material={nodes.Cube153.material} position={[4, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube154.geometry} material={nodes.Cube154.material} position={[5, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube155.geometry} material={nodes.Cube155.material} position={[-5, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube156.geometry} material={nodes.Cube156.material} position={[-4, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube157.geometry} material={nodes.Cube157.material} position={[-3, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube158.geometry} material={nodes.Cube158.material} position={[-2, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube159.geometry} material={nodes.Cube159.material} position={[-1, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube160.geometry} material={nodes.Cube160.material} position={[-6, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Cube161.geometry} material={nodes.Cube161.material} position={[6, 0.5, 7.653]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.wall_corner_1.geometry} material={nodes.wall_corner_1.material} position={[13.3, 0, 0]} />
                <mesh geometry={nodes.wall_corner.geometry} material={nodes.wall_corner.material} />
            </group>
            <group ref={desk_group_ref}>

                <mesh geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} />
                <mesh geometry={nodes.Cube164.geometry} material={nodes.Cube164.material} position={[1.57, 0.225, 1.4]} scale={[3.314, 1, 1]} />
                <mesh geometry={nodes.Cube165.geometry} material={nodes.Cube165.material} position={[-1.57, 0.225, 1.4]} scale={[3.314, 1, 1]} />
            </group>
            <group ref={monitor_group_ref}>
                <mesh geometry={nodes.Cube175.geometry} material={nodes.Cube175.material} position={[-1.335, 1.045, 1.163]} rotation={[0, -0.392, 0]} scale={[0.396, 0.016, 0.396]} />
                <mesh geometry={nodes.Cube176.geometry} material={nodes.Cube176.material} position={[1.333, 1.045, 1.071]} rotation={[0, 0.442, 0]} scale={[0.396, 0.016, 0.396]} />
                <mesh geometry={nodes['5_mon'].geometry} material={nodes['5_mon'].material} position={[-0.079, 0.609, -0.254]} scale={1.203} />
                <mesh geometry={nodes['5_mon_screens'].geometry} material={nodes['5_mon_screens'].material} position={[-0.079, 0.609, -0.254]} scale={1.203} />
            </group>

            <group ref={wallmonitors_group_ref}>


                <mesh geometry={nodes.Cube177.geometry} material={nodes.Cube177.material} position={[-0.001, 5.384, 7.556]} scale={[21.287, 3.642, 0.101]} />
                <mesh geometry={nodes.Cube162.geometry} material={nodes.Cube162.material} position={[-0.001, 2.876, 7.556]} scale={[15.254, 5.963, 0.101]} />
                <mesh geometry={nodes.Cube163.geometry} material={nodes.Cube163.material} position={[-4.591, 2.702, 7.556]} scale={[2.927, 5.267, 0.101]} />
                <mesh geometry={nodes.Cube178.geometry} material={nodes.Cube178.material} position={[4.589, 2.702, 7.556]} scale={[2.927, 5.267, 0.101]} />
                <mesh geometry={nodes.Cube179.geometry} material={nodes.Cube179.material} position={[-6.502, 3.376, 3.62]} rotation={[0, Math.PI / 2, 0]} scale={[13.42, 7.149, 0.101]} />
                <mesh geometry={nodes.Cube180.geometry} material={nodes.Cube180.material} position={[6.502, 3.376, 3.62]} rotation={[0, Math.PI / 2, 0]} scale={[13.42, 7.149, 0.101]} />
            </group>

            <group ref={couch_group_ref}>
                <mesh geometry={nodes.Cube166.geometry} material={nodes.Cube166.material} />
                <mesh geometry={nodes.Cube167.geometry} material={nodes.Cube167.material} position={[0, 0, -2.41]} />
                <mesh geometry={nodes.Cube168.geometry} material={nodes.Cube168.material} position={[0, 0, -4.813]} />
                <mesh geometry={nodes.Cube169.geometry} material={nodes.Cube169.material} position={[-11.752, 0, 0]} />
                <mesh geometry={nodes.Cube170.geometry} material={nodes.Cube170.material} position={[-11.752, 0, -2.41]} />
                <mesh geometry={nodes.Cube171.geometry} material={nodes.Cube171.material} position={[-11.752, 0, -4.813]} />
                <mesh geometry={nodes.Cube172.geometry} material={nodes.Cube172.material} position={[-2.222, 0, 12.762]} rotation={[0, Math.PI / 2, 0]} />
                <mesh geometry={nodes.Cube173.geometry} material={nodes.Cube173.material} position={[-4.632, 0, 12.762]} rotation={[0, Math.PI / 2, 0]} />
                <mesh geometry={nodes.Cube174.geometry} material={nodes.Cube174.material} position={[-10.342, 0, 12.762]} rotation={[0, Math.PI / 2, 0]} />
            </group>

        </group>

    );
}
