/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef } from 'react';
import {  useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { Color } from 'three'

import { Object3D } from 'three'; // Import Object3D class from Three.js


export default function HutModel(props) {
    const { nodes } = useGLTF("./github.glb");

    const logo_ref = useRef();

    let github_color = new Color('#6E5494');

    const open_github = () => {
        const confirmed = window.confirm("Are you sure you want to open the GitHub profile?");
        if (confirmed) {
            window.open("https://github.com/MaxwellVolz");
        }
    }
    const spotlight_ref = useRef();
    const spotlightTarget = new Object3D();
    spotlightTarget.position.set(2, 0, 2); // Replace with your desired coordinates


    useFrame(({ clock }) => {
        // const a = clock.getElapsedTime();
    })

    return (
        <group {...props} ref={logo_ref} dispose={null} >

            <group rotation={[0, Math.PI / 4, 0]} scale={[.04, .1, 0.04]} position={[2, .7, 2]}>
                <mesh geometry={nodes.Github_logo.geometry} material={nodes.Github_logo.material}>
                    <meshPhongMaterial color={github_color} />
                </mesh>
                <mesh scale={[76, 1, 20]} position={[0, -2, 0]} onClick={() => open_github()}>
                    <boxGeometry />
                    <meshPhongMaterial opacity={0.0} transparent={true} />
                </mesh>
            </group>
        </group>
    );
}
