/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense, useEffect } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'


const useAnimateGroup = (groupRef, options) => {
  useEffect(() => {
    if (groupRef.current) {
      groupRef.current.children.forEach(mesh => {
        mesh.userData.initialY = mesh.position.y;
        mesh.userData.targetY = Math.random() * (options.range) + options.min;
        mesh.userData.animationProgress = 0;
      });
    }
  }, [groupRef, options]);

  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.children.forEach(mesh => {
        if (mesh.userData.animationProgress < 1) {
          mesh.userData.animationProgress += delta / options.duration;
          const progress = mesh.userData.animationProgress;
          mesh.position.y = mesh.userData.initialY + (mesh.userData.targetY - mesh.userData.initialY) * progress;

          // Reset animation if complete
          if (progress >= 1) {
            mesh.userData.initialY = mesh.userData.targetY;
            mesh.userData.targetY = options.resetTargetY;
            mesh.userData.animationProgress = 0;
          }
        }
      });
    }
  });
};


export default function Gamer(props) {

  const { nodes, materials } = useGLTF("./models/gamer.glb");

  const mesh_ref = useRef();
  const floor_group_ref = useRef();
  const wall_group_ref = useRef();
  const desk_group_ref = useRef();
  const monitor_group_ref = useRef();
  const couch_group_ref = useRef();
  const wallmonitors_group_ref = useRef();

  // Use the hook for floor group
  useAnimateGroup(floor_group_ref, { range: -20, min: -10, duration: 2.2, resetTargetY: 0 });

  // Use the hook for wall group
  useAnimateGroup(wall_group_ref, { range: 20, min: 10, duration: 2, resetTargetY: 0.5 });

  useAnimateGroup(desk_group_ref, { range: 20, min: 10, duration: 2.3, resetTargetY: 0 });
  useAnimateGroup(monitor_group_ref, { range: 21, min: 20, duration: 2.4, resetTargetY: 0.5 });
  useAnimateGroup(couch_group_ref, { range: 30, min: 20, duration: 2.5, resetTargetY: 0.1 });
  useAnimateGroup(wallmonitors_group_ref, { range: 30, min: 20, duration: 2.6, resetTargetY: 3.5 });

  const open_github = () => {
    window.open("https://github.com/MaxwellVolz")
  }

  return (

    <group {...props} dispose={null} scale={1}>
      <group ref={floor_group_ref}>
        <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
        <mesh geometry={nodes.floor_tile_001.geometry} material={nodes.floor_tile_001.material} />
        <mesh geometry={nodes.floor_tile_002.geometry} material={nodes.floor_tile_002.material} />
        <mesh geometry={nodes.floor_tile_003.geometry} material={nodes.floor_tile_003.material} />
        <mesh geometry={nodes.floor_tile_004.geometry} material={nodes.floor_tile_004.material} />
        <mesh geometry={nodes.floor_tile_005.geometry} material={nodes.floor_tile_005.material} />
        <mesh geometry={nodes.floor_tile_006.geometry} material={nodes.floor_tile_006.material} />
        <mesh geometry={nodes.floor_tile_007.geometry} material={nodes.floor_tile_007.material} />
        <mesh geometry={nodes.floor_tile_008.geometry} material={nodes.floor_tile_008.material} />
        <mesh geometry={nodes.floor_tile_009.geometry} material={nodes.floor_tile_009.material} />
        <mesh geometry={nodes.floor_tile_010.geometry} material={nodes.floor_tile_010.material} />
        <mesh geometry={nodes.floor_tile_011.geometry} material={nodes.floor_tile_011.material} />
        <mesh geometry={nodes.floor_tile_012.geometry} material={nodes.floor_tile_012.material} />
        <mesh geometry={nodes.floor_tile_013.geometry} material={nodes.floor_tile_013.material} />
        <mesh geometry={nodes.floor_tile_014.geometry} material={nodes.floor_tile_014.material} />
        <mesh geometry={nodes.floor_tile_015.geometry} material={nodes.floor_tile_015.material} />
        <mesh geometry={nodes.floor_tile_016.geometry} material={nodes.floor_tile_016.material} />
        <mesh geometry={nodes.floor_tile_017.geometry} material={nodes.floor_tile_017.material} />
        <mesh geometry={nodes.floor_tile_018.geometry} material={nodes.floor_tile_018.material} />
        <mesh geometry={nodes.floor_tile_019.geometry} material={nodes.floor_tile_019.material} />
        <mesh geometry={nodes.floor_tile_020.geometry} material={nodes.floor_tile_020.material} />
        <mesh geometry={nodes.floor_tile_021.geometry} material={nodes.floor_tile_021.material} />
        <mesh geometry={nodes.floor_tile_022.geometry} material={nodes.floor_tile_022.material} />
        <mesh geometry={nodes.floor_tile_023.geometry} material={nodes.floor_tile_023.material} />
        <mesh geometry={nodes.floor_tile_024.geometry} material={nodes.floor_tile_024.material} />
        <mesh geometry={nodes.floor_tile_025.geometry} material={nodes.floor_tile_025.material} />
        <mesh geometry={nodes.floor_tile_026.geometry} material={nodes.floor_tile_026.material} />
        <mesh geometry={nodes.floor_tile_027.geometry} material={nodes.floor_tile_027.material} />
        <mesh geometry={nodes.floor_tile_028.geometry} material={nodes.floor_tile_028.material} />
        <mesh geometry={nodes.floor_tile_029.geometry} material={nodes.floor_tile_029.material} />
        <mesh geometry={nodes.floor_tile_030.geometry} material={nodes.floor_tile_030.material} />
        <mesh geometry={nodes.floor_tile_031.geometry} material={nodes.floor_tile_031.material} />
        <mesh geometry={nodes.floor_tile_032.geometry} material={nodes.floor_tile_032.material} />
        <mesh geometry={nodes.floor_tile_033.geometry} material={nodes.floor_tile_033.material} />
        <mesh geometry={nodes.floor_tile_034.geometry} material={nodes.floor_tile_034.material} />
        <mesh geometry={nodes.floor_tile_035.geometry} material={nodes.floor_tile_035.material} />
        <mesh geometry={nodes.floor_tile_036.geometry} material={nodes.floor_tile_036.material} />
        <mesh geometry={nodes.floor_tile_037.geometry} material={nodes.floor_tile_037.material} />
        <mesh geometry={nodes.floor_tile_038.geometry} material={nodes.floor_tile_038.material} />
        <mesh geometry={nodes.floor_tile_039.geometry} material={nodes.floor_tile_039.material} />
        <mesh geometry={nodes.floor_tile_040.geometry} material={nodes.floor_tile_040.material} />
        <mesh geometry={nodes.floor_tile_041.geometry} material={nodes.floor_tile_041.material} />
        <mesh geometry={nodes.floor_tile_042.geometry} material={nodes.floor_tile_042.material} />
        <mesh geometry={nodes.floor_tile_043.geometry} material={nodes.floor_tile_043.material} />
        <mesh geometry={nodes.floor_tile_044.geometry} material={nodes.floor_tile_044.material} />
        <mesh geometry={nodes.floor_tile_045.geometry} material={nodes.floor_tile_045.material} />
        <mesh geometry={nodes.floor_tile_046.geometry} material={nodes.floor_tile_046.material} />
        <mesh geometry={nodes.floor_tile_047.geometry} material={nodes.floor_tile_047.material} />
        <mesh geometry={nodes.floor_tile_048.geometry} material={nodes.floor_tile_048.material} />
        <mesh geometry={nodes.floor_tile_049.geometry} material={nodes.floor_tile_049.material} />
        <mesh geometry={nodes.floor_tile_050.geometry} material={nodes.floor_tile_050.material} />
        <mesh geometry={nodes.floor_tile_051.geometry} material={nodes.floor_tile_051.material} />
        <mesh geometry={nodes.floor_tile_052.geometry} material={nodes.floor_tile_052.material} />
        <mesh geometry={nodes.floor_tile_053.geometry} material={nodes.floor_tile_053.material} />
        <mesh geometry={nodes.floor_tile_054.geometry} material={nodes.floor_tile_054.material} />
        <mesh geometry={nodes.floor_tile_055.geometry} material={nodes.floor_tile_055.material} />
        <mesh geometry={nodes.floor_tile_056.geometry} material={nodes.floor_tile_056.material} />
        <mesh geometry={nodes.floor_tile_057.geometry} material={nodes.floor_tile_057.material} />
        <mesh geometry={nodes.floor_tile_058.geometry} material={nodes.floor_tile_058.material} />
        <mesh geometry={nodes.floor_tile_059.geometry} material={nodes.floor_tile_059.material} />
        <mesh geometry={nodes.floor_tile_060.geometry} material={nodes.floor_tile_060.material} />
        <mesh geometry={nodes.floor_tile_061.geometry} material={nodes.floor_tile_061.material} />
        <mesh geometry={nodes.floor_tile_062.geometry} material={nodes.floor_tile_062.material} />
        <mesh geometry={nodes.floor_tile_063.geometry} material={nodes.floor_tile_063.material} />
        <mesh geometry={nodes.floor_tile_064.geometry} material={nodes.floor_tile_064.material} />
        <mesh geometry={nodes.floor_tile_065.geometry} material={nodes.floor_tile_065.material} />
        <mesh geometry={nodes.floor_tile_066.geometry} material={nodes.floor_tile_066.material} />
        <mesh geometry={nodes.floor_tile_067.geometry} material={nodes.floor_tile_067.material} />
        <mesh geometry={nodes.floor_tile_068.geometry} material={nodes.floor_tile_068.material} />
        <mesh geometry={nodes.floor_tile_069.geometry} material={nodes.floor_tile_069.material} />
        <mesh geometry={nodes.floor_tile_070.geometry} material={nodes.floor_tile_070.material} />
        <mesh geometry={nodes.floor_tile_071.geometry} material={nodes.floor_tile_071.material} />
        <mesh geometry={nodes.floor_tile_072.geometry} material={nodes.floor_tile_072.material} />
        <mesh geometry={nodes.floor_tile_073.geometry} material={nodes.floor_tile_073.material} />
        <mesh geometry={nodes.floor_tile_074.geometry} material={nodes.floor_tile_074.material} />
        <mesh geometry={nodes.floor_tile_075.geometry} material={nodes.floor_tile_075.material} />
        <mesh geometry={nodes.floor_tile_076.geometry} material={nodes.floor_tile_076.material} />
        <mesh geometry={nodes.floor_tile_078.geometry} material={nodes.floor_tile_078.material} />
        <mesh geometry={nodes.floor_tile_079.geometry} material={nodes.floor_tile_079.material} />
        <mesh geometry={nodes.floor_tile_080.geometry} material={nodes.floor_tile_080.material} />
        <mesh geometry={nodes.floor_tile_081.geometry} material={nodes.floor_tile_081.material} />
        <mesh geometry={nodes.floor_tile_082.geometry} material={nodes.floor_tile_082.material} />
        <mesh geometry={nodes.floor_tile_083.geometry} material={nodes.floor_tile_083.material} />
        <mesh geometry={nodes.floor_tile_084.geometry} material={nodes.floor_tile_084.material} />
        <mesh geometry={nodes.floor_tile_085.geometry} material={nodes.floor_tile_085.material} />
        <mesh geometry={nodes.floor_tile_086.geometry} material={nodes.floor_tile_086.material} />
        <mesh geometry={nodes.floor_tile_087.geometry} material={nodes.floor_tile_087.material} />
        <mesh geometry={nodes.floor_tile_088.geometry} material={nodes.floor_tile_088.material} />
        <mesh geometry={nodes.floor_tile_089.geometry} material={nodes.floor_tile_089.material} />
        <mesh geometry={nodes.floor_tile_090.geometry} material={nodes.floor_tile_090.material} />
        <mesh geometry={nodes.floor_tile_091.geometry} material={nodes.floor_tile_091.material} />
        <mesh geometry={nodes.floor_tile_092.geometry} material={nodes.floor_tile_092.material} />
        <mesh geometry={nodes.floor_tile_093.geometry} material={nodes.floor_tile_093.material} />
        <mesh geometry={nodes.floor_tile_094.geometry} material={nodes.floor_tile_094.material} />
        <mesh geometry={nodes.floor_tile_095.geometry} material={nodes.floor_tile_095.material} />
        <mesh geometry={nodes.floor_tile_096.geometry} material={nodes.floor_tile_096.material} />
        <mesh geometry={nodes.floor_tile_097.geometry} material={nodes.floor_tile_097.material} />
        <mesh geometry={nodes.floor_tile_098.geometry} material={nodes.floor_tile_098.material} />
        <mesh geometry={nodes.floor_tile_099.geometry} material={nodes.floor_tile_099.material} />
        <mesh geometry={nodes.floor_tile_100.geometry} material={nodes.floor_tile_100.material} />
        <mesh geometry={nodes.floor_tile_101.geometry} material={nodes.floor_tile_101.material} />
        <mesh geometry={nodes.floor_tile_102.geometry} material={nodes.floor_tile_102.material} />
        <mesh geometry={nodes.floor_tile_103.geometry} material={nodes.floor_tile_103.material} />
        <mesh geometry={nodes.floor_tile_104.geometry} material={nodes.floor_tile_104.material} />
        <mesh geometry={nodes.floor_tile_105.geometry} material={nodes.floor_tile_105.material} />
        <mesh geometry={nodes.floor_tile_106.geometry} material={nodes.floor_tile_106.material} />
        <mesh geometry={nodes.floor_tile_107.geometry} material={nodes.floor_tile_107.material} />
        <mesh geometry={nodes.floor_tile_108.geometry} material={nodes.floor_tile_108.material} />
        <mesh geometry={nodes.floor_tile_109.geometry} material={nodes.floor_tile_109.material} />
        <mesh geometry={nodes.floor_tile_110.geometry} material={nodes.floor_tile_110.material} />
        <mesh geometry={nodes.floor_tile_111.geometry} material={nodes.floor_tile_111.material} />
        <mesh geometry={nodes.floor_tile_112.geometry} material={nodes.floor_tile_112.material} />
        <mesh geometry={nodes.floor_tile_113.geometry} material={nodes.floor_tile_113.material} />
        <mesh geometry={nodes.floor_tile_114.geometry} material={nodes.floor_tile_114.material} />
        <mesh geometry={nodes.floor_tile_115.geometry} material={nodes.floor_tile_115.material} />
        <mesh geometry={nodes.floor_tile_116.geometry} material={nodes.floor_tile_116.material} />
        <mesh geometry={nodes.floor_tile_117.geometry} material={nodes.floor_tile_117.material} />
        <mesh geometry={nodes.floor_tile_118.geometry} material={nodes.floor_tile_118.material} />
        <mesh geometry={nodes.floor_tile_119.geometry} material={nodes.floor_tile_119.material} />
        <mesh geometry={nodes.floor_tile_120.geometry} material={nodes.floor_tile_120.material} />
        <mesh geometry={nodes.floor_tile_121.geometry} material={nodes.floor_tile_121.material} />
        <mesh geometry={nodes.floor_tile_122.geometry} material={nodes.floor_tile_122.material} />
        <mesh geometry={nodes.floor_tile_123.geometry} material={nodes.floor_tile_123.material} />
        <mesh geometry={nodes.floor_tile_124.geometry} material={nodes.floor_tile_124.material} />
        <mesh geometry={nodes.floor_tile_125.geometry} material={nodes.floor_tile_125.material} />
        <mesh geometry={nodes.floor_tile_126.geometry} material={nodes.floor_tile_126.material} />
        <mesh geometry={nodes.floor_tile_127.geometry} material={nodes.floor_tile_127.material} />
        <mesh geometry={nodes.floor_tile_128.geometry} material={nodes.floor_tile_128.material} />
        <mesh geometry={nodes.floor_tile_129.geometry} material={nodes.floor_tile_129.material} />
        <mesh geometry={nodes.floor_tile_130.geometry} material={nodes.floor_tile_130.material} />
      </group>

      <group ref={wall_group_ref}>
        <mesh geometry={nodes.wall_131.geometry} material={nodes.wall_131.material} />
        <mesh geometry={nodes.wall_132.geometry} material={nodes.wall_132.material} />
        <mesh geometry={nodes.wall_133.geometry} material={nodes.wall_133.material} />
        <mesh geometry={nodes.wall_134.geometry} material={nodes.wall_134.material} />
        <mesh geometry={nodes.wall_135.geometry} material={nodes.wall_135.material} />
        <mesh geometry={nodes.wall_136.geometry} material={nodes.wall_136.material} />
        <mesh geometry={nodes.wall_137.geometry} material={nodes.wall_137.material} />
        <mesh geometry={nodes.wall_138.geometry} material={nodes.wall_138.material} />
        <mesh geometry={nodes.wall_139.geometry} material={nodes.wall_139.material} />
        <mesh geometry={nodes.wall_140.geometry} material={nodes.wall_140.material} />
        <mesh geometry={nodes.wall_141.geometry} material={nodes.wall_141.material} />
        <mesh geometry={nodes.wall_142.geometry} material={nodes.wall_142.material} />
        <mesh geometry={nodes.wall_143.geometry} material={nodes.wall_143.material} />
        <mesh geometry={nodes.wall_144.geometry} material={nodes.wall_144.material} />
        <mesh geometry={nodes.wall_145.geometry} material={nodes.wall_145.material} />
        <mesh geometry={nodes.wall_146.geometry} material={nodes.wall_146.material} />
        <mesh geometry={nodes.wall_147.geometry} material={nodes.wall_147.material} />
        <mesh geometry={nodes.wall_148.geometry} material={nodes.wall_148.material} />
        <mesh geometry={nodes.wall_149.geometry} material={nodes.wall_149.material} />
        <mesh geometry={nodes.wall_150.geometry} material={nodes.wall_150.material} />
        <mesh geometry={nodes.wall_151.geometry} material={nodes.wall_151.material} />
        <mesh geometry={nodes.wall_152.geometry} material={nodes.wall_152.material} />
        <mesh geometry={nodes.wall_153.geometry} material={nodes.wall_153.material} />
        <mesh geometry={nodes.wall_154.geometry} material={nodes.wall_154.material} />
        <mesh geometry={nodes.wall_155.geometry} material={nodes.wall_155.material} />
        <mesh geometry={nodes.wall_156.geometry} material={nodes.wall_156.material} />
        <mesh geometry={nodes.wall_157.geometry} material={nodes.wall_157.material} />
        <mesh geometry={nodes.wall_158.geometry} material={nodes.wall_158.material} />
        <mesh geometry={nodes.wall_159.geometry} material={nodes.wall_159.material} />
        <mesh geometry={nodes.wall_160.geometry} material={nodes.wall_160.material} />
        <mesh geometry={nodes.wall_161.geometry} material={nodes.wall_161.material} />
        <mesh geometry={nodes.wall_corner_1.geometry} material={nodes.wall_corner_1.material} />
        <mesh geometry={nodes.wall_corner.geometry} material={nodes.wall_corner.material} />
      </group>

      <group ref={desk_group_ref}>
        <mesh geometry={nodes.desk_top.geometry} material={nodes.desk_top.material} />
        <mesh geometry={nodes.left_cabinet.geometry} material={nodes.left_cabinet.material} />
        <mesh geometry={nodes.right_cabinet.geometry} material={nodes.right_cabinet.material} />
      </group>

      <group ref={monitor_group_ref}>
        <mesh geometry={nodes['5_mon'].geometry} material={nodes['5_mon'].material} />
        <mesh geometry={nodes['5_mon_screens'].geometry} material={nodes['5_mon_screens'].material} />
        <mesh geometry={nodes.mon_stand.geometry} material={nodes.mon_stand.material} />
        <mesh geometry={nodes.mon_stand2.geometry} material={nodes.mon_stand2.material} />
      </group>

      <group ref={wall_monitor_group_ref}>
        <mesh geometry={nodes.top_monitor.geometry} material={nodes.top_monitor.material} />
        <mesh geometry={nodes.center_monitor.geometry} material={nodes.center_monitor.material} />
        <mesh geometry={nodes.right_vertical_monitor.geometry} material={nodes.right_vertical_monitor.material} />
        <mesh geometry={nodes.left_vertical_monitor.geometry} material={nodes.left_vertical_monitor.material} />
        <mesh geometry={nodes.right_monitor.geometry} material={nodes.right_monitor.material} />
        <mesh geometry={nodes.left_monitor.geometry} material={nodes.left_monitor.material} />
        <mesh geometry={nodes.left_screen.geometry} material={nodes.left_screen.material} />
        <mesh geometry={nodes.right_screen.geometry} material={nodes.right_screen.material} />
        <mesh geometry={nodes.center_screen.geometry} material={nodes.center_screen.material} />
        <mesh geometry={nodes.right_vertical_screen.geometry} material={nodes.right_vertical_screen.material} />
        <mesh geometry={nodes.left_vertical_screen.geometry} material={nodes.left_vertical_screen.material} />
        <mesh geometry={nodes.top_screen.geometry} material={nodes.top_screen.material} />

      </group>
      <group ref={couch_group_ref}>


        <mesh geometry={nodes.couch001.geometry} material={nodes.couch001.material} />
        <mesh geometry={nodes.couch002.geometry} material={nodes.couch002.material} />
        <mesh geometry={nodes.couch003.geometry} material={nodes.couch003.material} />
        <mesh geometry={nodes.couch004.geometry} material={nodes.couch004.material} />
        <mesh geometry={nodes.couch005.geometry} material={nodes.couch005.material} />
        <mesh geometry={nodes.couch006.geometry} material={nodes.couch006.material} />
        <mesh geometry={nodes.couch007.geometry} material={nodes.couch007.material} />
        <mesh geometry={nodes.couch008.geometry} material={nodes.couch008.material} />
        <mesh geometry={nodes.couch.geometry} material={nodes.couch.material} />
      </group>
    </group>


  );
}